/**
 * Purpose: Presents the admin queue with scores, disagreement, campaign
 * similarity, feedback state, summary counts, and searchable submissions.
 */
import {useEffect,useState} from 'react';
import {ArrowRight,Search} from 'lucide-react';
import {Link} from 'react-router-dom';
import {api} from '../api';
import {Badge} from '../components';

// Loads, filters, summarizes, and renders administrator submissions.
export default function Dashboard(){const[items,setItems]=useState([]),[query,setQuery]=useState(''),[error,setError]=useState('');useEffect(()=>{api.adminList().then(setItems).catch(e=>setError(e.message))},[]);const shown=items.filter(x=>`${x.name} ${x.email} ${x.service_title} ${x.feedback_verdict||''}`.toLowerCase().includes(query.toLowerCase()));return <><header><div><p className="eyebrow">ADMIN SPAM REVIEW</p><h1>Automatically screened services</h1><p>Review score evidence, model disagreement, coordinated campaigns, and human feedback.</p></div></header><section className="stats innovation-stats"><div><span>Total screened</span><strong>{items.length}</strong></div><div><span>High spam risk</span><strong className="risk-text">{items.filter(x=>x.risk_level==='high').length}</strong></div><div><span>High disagreement</span><strong>{items.filter(x=>x.disagreement_level==='high').length}</strong></div><div><span>Campaign-linked</span><strong>{items.filter(x=>x.similar_count>0).length}</strong></div></section><section className="panel"><div className="toolbar"><div className="search"><Search size={18}/><input aria-label="Search submissions" placeholder="Search vendor, service, or feedback" value={query} onChange={e=>setQuery(e.target.value)}/></div></div>{error?<p className="error">{error}</p>:<div className="table-wrap"><table><thead><tr><th>Vendor</th><th>Service / package</th><th>Trust</th><th>Spam risk</th><th>AI agreement</th><th>Cluster</th><th>Feedback</th><th></th></tr></thead><tbody>{shown.map(x=><tr key={x.id}><td><b>{x.name}</b><small>{x.email}</small></td><td>{x.service_title}<small>{x.category}</small></td><td>{x.trust_score??'—'} / 10</td><td>{x.risk_level?<Badge level={x.risk_level}/>:<span>Screening…</span>}</td><td><span className={`mini-status ${x.disagreement_level}`}>{x.disagreement_level||'—'}</span></td><td>{x.similar_count?`${x.similar_count} related`:'None'}</td><td>{x.feedback_verdict?.replaceAll('_',' ')||'Not reviewed'}</td><td><Link to={`/admin/submissions/${x.id}`} aria-label={`Review ${x.name}`}><ArrowRight size={19}/></Link></td></tr>)}</tbody></table></div>}</section></>}
