/**
 * Purpose: Presents the admin queue with AI-only scores, scoring-model
 * provenance, campaign similarity, feedback state, and searchable submissions.
 */
import {useEffect,useState} from 'react';
import {ArrowRight,Search} from 'lucide-react';
import {Link} from 'react-router-dom';
import {api} from '../api';
import {Badge} from '../components';

// Loads, filters, summarizes, and renders administrator submissions.
export default function Dashboard(){const[items,setItems]=useState([]),[query,setQuery]=useState(''),[error,setError]=useState('');useEffect(()=>{api.adminList().then(setItems).catch(e=>setError(e.message))},[]);const shown=items.filter(x=>`${x.name} ${x.email} ${x.service_title} ${x.scoring_model||''} ${x.feedback_verdict||''}`.toLowerCase().includes(query.toLowerCase()));return <><header><div><p className="eyebrow">ADMIN SPAM REVIEW</p><h1>AI-screened services</h1><p>Final scores come only from local AI. Evidence detectors have zero scoring weight.</p></div></header><section className="stats innovation-stats"><div><span>Total submissions</span><strong>{items.length}</strong></div><div><span>High AI spam risk</span><strong className="risk-text">{items.filter(x=>x.risk_level==='high').length}</strong></div><div><span>Qwen fallbacks</span><strong>{items.filter(x=>x.fallback_used).length}</strong></div><div><span>AI unavailable</span><strong>{items.filter(x=>x.assessment_status==='ai_unavailable').length}</strong></div></section><section className="panel"><div className="toolbar"><div className="search"><Search size={18}/><input aria-label="Search submissions" placeholder="Search vendor, service, model, or feedback" value={query} onChange={e=>setQuery(e.target.value)}/></div></div>{error?<p className="error">{error}</p>:<div className="table-wrap"><table><thead><tr><th>Vendor</th><th>Service / package</th><th>Trust</th><th>Spam risk</th><th>AI scorer</th><th>Cluster</th><th>Feedback</th><th></th></tr></thead><tbody>{shown.map(x=><tr key={x.id}><td><b>{x.name}</b><small>{x.email}</small></td><td>{x.service_title}<small>{x.category}</small></td><td>{x.trust_score??'—'} / 10</td><td>{x.risk_level&&x.risk_level!=='unavailable'?<Badge level={x.risk_level}/>:<span>AI unavailable</span>}</td><td><span className={`mini-status ${x.fallback_used?'medium':x.scoring_model?'low':'high'}`}>{x.scoring_model||'Unavailable'}{x.fallback_used?' · fallback':''}</span></td><td>{x.similar_count?`${x.similar_count} related`:'None'}</td><td>{x.feedback_verdict?.replaceAll('_',' ')||'Not reviewed'}</td><td><Link to={`/admin/submissions/${x.id}`} aria-label={`Review ${x.name}`}><ArrowRight size={19}/></Link></td></tr>)}</tbody></table></div>}</section></>}
