/**
 * Purpose: Presents admin-only scoring, evidence, vendor address and protected
 * service uploads, campaign intelligence, and structured review feedback.
 */
import {useEffect,useState} from 'react';
import {ArrowLeft,CheckCircle2,Download,ShieldAlert} from 'lucide-react';
import {Link,useParams} from 'react-router-dom';
import {api} from '../api';
import {Badge,Score} from '../components';

// Renders one auditable score ledger with points and reasons.
function FactorTable({title,kind,items,total}){return <div className={`factor-panel ${kind}`}><div className="factor-title"><h2>{title}</h2><strong>{items.reduce((n,x)=>n+x.points,0).toFixed(1)} / {total}</strong></div>{items.map(x=><article key={x.code}><div><b>{x.label}</b><p>{x.reason}</p></div><span>{x.points.toFixed(1)} / {x.max_points}</span></article>)}</div>}
// Highlights exact deterministic spam phrases in submitted text.
function EvidenceText({field,text,evidence}){const spans=evidence.filter(x=>x.field===field).sort((a,b)=>a.start-b.start);if(!spans.length)return <>{text||'Not supplied'}</>;const output=[];let cursor=0;spans.forEach((span,index)=>{if(span.start<cursor)return;output.push(text.slice(cursor,span.start));output.push(<mark title={span.reason} key={index}>{text.slice(span.start,span.end)}</mark>);cursor=span.end});output.push(text.slice(cursor));return <>{output}</>}
// Loads protected images through authenticated requests and downloads documents safely.
function MediaGallery({images,file}){const[urls,setUrls]=useState([]),[error,setError]=useState('');useEffect(()=>{let active=true;const made=[];Promise.all((images||[]).map(async image=>({image,url:URL.createObjectURL(await api.adminUpload(image.storage_name))}))).then(items=>{items.forEach(x=>made.push(x.url));if(active)setUrls(items)}).catch(e=>active&&setError(e.message));return()=>{active=false;made.forEach(URL.revokeObjectURL)}},[images]);async function download(){try{const url=URL.createObjectURL(await api.adminUpload(file.storage_name));const link=document.createElement('a');link.href=url;link.download=file.original_name;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}catch(e){setError(e.message)}}return <section className="panel media-panel"><p className="eyebrow">SERVICE MEDIA</p><h2>Vendor uploads</h2>{error&&<p className="error">{error}</p>}<div className="media-grid">{urls.map(({image,url})=><figure key={image.storage_name}><img src={url} alt={image.original_name}/><figcaption>{image.original_name}</figcaption></figure>)}</div>{!urls.length&&<p>No service photos supplied.</p>}{file?<button className="button ghost" onClick={download}><Download size={17}/>Download {file.original_name}</button>:<p>No supporting file supplied.</p>}</section>}

// Loads the assessment and records approval or structured feedback.
export default function Detail(){const{id}=useParams();const[item,setItem]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState('');const[feedback,setFeedback]=useState({verdict:'needs_review',notes:'',factor_codes:[]});useEffect(()=>{api.adminGet(id).then(setItem).catch(e=>setError(e.message))},[id]);async function approve(){setBusy(true);try{setItem(await api.approve(id))}catch(e){setError(e.message)}finally{setBusy(false)}}async function submitFeedback(e){e.preventDefault();setBusy(true);try{setItem(await api.feedback(id,feedback));setFeedback({...feedback,notes:''})}catch(e){setError(e.message)}finally{setBusy(false)}}function toggleFactor(code){setFeedback({...feedback,factor_codes:feedback.factor_codes.includes(code)?feedback.factor_codes.filter(x=>x!==code):[...feedback.factor_codes,code]})}if(error&&!item)return <p className="error">{error}</p>;if(!item)return <p>Loading…</p>;const intel=item.intelligence||{},provenance=intel.model_provenance||{},campaign=item.campaign||{matches:[]},evidence=intel.evidence_map||[],deterministic=[...(intel.deterministic_evidence?.risk_evidence||[]),...(intel.deterministic_evidence?.trust_evidence||[])].filter(x=>x.triggered||x.earned);return <><Link className="back" to="/admin"><ArrowLeft size={17}/>Back to queue</Link>
  <header><div><p className="eyebrow">AUTOMATIC SPAM ASSESSMENT</p><h1>{item.name}</h1><p>{item.service_title} · {item.category}</p></div><div className="actions"><Badge level={item.risk_level}/>{item.status!=='approved'&&<button disabled={busy} className="button primary" onClick={approve}>{busy?'Saving…':'Approve service'}</button>}</div></header>{error&&<p className="error">{error}</p>}
  <section className="mandatory panel"><div><p className="eyebrow">MANDATORY SCORING SERVICES</p><h2>All automatic checks</h2></div>{item.mandatory_services.map(s=><span key={s.code}><CheckCircle2 size={16}/>{s.name}<b>Required</b></span>)}</section>
  <section className="score-panel panel"><Score label="Trust Score" value={item.trust_score} type="trust"/><Score label="Spam Risk Score" value={item.risk_score} type="risk"/><div className="confidence"><span>{item.combined_assessment.method}</span><strong>{item.confidence}% confidence</strong></div></section>
  <section className="intelligence-grid"><div className={`panel insight model-${provenance.fallback_used?'fallback':provenance.status}`}><p className="eyebrow">AI SCORING MODEL</p><h2>{provenance.model||'No model available'}</h2><p>{provenance.status!=='complete'?'Both local scoring models failed; approval is blocked.':provenance.fallback_used?'Qwen fallback was used after Llama failed.':'Primary Llama model used.'}</p><small>Final scores are AI-only. Deterministic checks have zero scoring weight.</small></div><div className="panel insight"><p className="eyebrow">CAMPAIGN CLUSTER</p><h2>{campaign.campaign_id||'No related campaign'}</h2><p><b>{campaign.similar_count||0}</b> similar submission(s)</p></div></section>
  <section className="factor-grid"><FactorTable title="Spam Risk Factors" kind="risk" items={item.risk_factors} total={10}/><FactorTable title="Trust Score Factors" kind="trust" items={item.trust_factors} total={10}/></section>
  <section className="panel evidence-panel"><p className="eyebrow">SPAM EVIDENCE MAP</p><h2>Submitted content with exact evidence matches</h2><p className="evidence-help">Deterministic findings below have zero scoring weight. Final scores come only from the named AI model.</p><dl><dt>Title</dt><dd><EvidenceText field="service_title" text={item.service_title} evidence={evidence}/></dd><dt>Description</dt><dd><EvidenceText field="description" text={item.description} evidence={evidence}/></dd><dt>Package</dt><dd><EvidenceText field="package_details" text={item.package_details} evidence={evidence}/></dd><dt>Offer</dt><dd><EvidenceText field="special_offer" text={item.special_offer} evidence={evidence}/></dd></dl><h3>Zero-weight detector findings</h3><ul>{deterministic.map(finding=><li key={finding.code}><b>{finding.label}:</b> {finding.reason} <small>(weight 0)</small></li>)}</ul><h3>Local AI semantic evidence</h3><ul>{(intel.ai_evidence||[]).map((reason,index)=><li key={index}>{reason}</li>)}</ul></section>
  <section className="panel counterfactual"><p className="eyebrow">WHY THIS SCORE?</p><h2>Estimated risk without each triggered factor</h2>{(intel.counterfactuals||[]).length?<div className="counter-list">{intel.counterfactuals.map(x=><div key={x.factor_code}><span>{x.label}</span><b>{x.current_risk} → {x.estimated_risk_without_factor}</b><small>−{x.estimated_reduction} estimated</small></div>)}</div>:<p>No triggered deterministic risk factor to remove.</p>}</section>
  <section className="detail-grid"><div className="panel profile"><h2>Business verification</h2><dl><dt>Address</dt><dd>{item.address_line1}<br/>{item.address_line2}<br/>{item.city}, {item.state}, {item.country} – {item.pincode}</dd><dt>Aadhaar</dt><dd>{item.aadhaar_number?`•••• •••• ${item.aadhaar_number.slice(-4)}`:'Not supplied'}</dd><dt>GSTIN</dt><dd>{item.gst_number||'Not supplied'}</dd><dt>Package</dt><dd>{item.package_name||'Not supplied'}</dd><dt>Price</dt><dd>{item.price_or_range||'Not supplied'}</dd><dt>Website</dt><dd>{item.website||'Not supplied'}</dd><dt>Portfolio</dt><dd>{item.portfolio_link?<a href={item.portfolio_link} target="_blank" rel="noreferrer">{item.portfolio_link}</a>:'Not supplied'}</dd></dl></div><div className="panel ai-card"><p className="eyebrow">LOCAL AI SPAM REVIEW</p><h2>{item.ai_assessment.model}</h2>{item.ai_assessment.status==='complete'?<><p><b>Spam probability: {item.ai_assessment.spam_probability}%</b></p><p>{item.ai_assessment.summary}</p></>:<p><ShieldAlert size={16}/> {item.ai_assessment.spam_indicators[0]}</p>}</div></section>
  <MediaGallery images={item.images} file={item.file}/>
  {campaign.matches?.length>0&&<section className="panel matches"><p className="eyebrow">RELATED SUBMISSIONS</p><h2>Possible coordinated campaign</h2>{campaign.matches.map(match=><Link key={match.id} to={`/admin/submissions/${match.id}`}><span><b>{match.name}</b><small>{match.service_title} · {match.reasons.join(', ')}</small></span><strong>{match.similarity}%</strong></Link>)}</section>}
  <section className="panel feedback-panel"><p className="eyebrow">ADMIN FEEDBACK LOOP</p><h2>Record review quality</h2><form onSubmit={submitFeedback}><select value={feedback.verdict} onChange={e=>setFeedback({...feedback,verdict:e.target.value})}><option value="needs_review">Needs review</option><option value="confirmed_spam">Confirmed spam</option><option value="false_positive">False positive</option><option value="accurate_low_risk">Accurate low risk</option></select><textarea maxLength="1000" placeholder="Reviewer notes" value={feedback.notes} onChange={e=>setFeedback({...feedback,notes:e.target.value})}/><div className="factor-picks">{item.risk_factors.filter(x=>x.triggered).map(x=><label key={x.code}><input type="checkbox" checked={feedback.factor_codes.includes(x.code)} onChange={()=>toggleFactor(x.code)}/>{x.label}</label>)}</div><button disabled={busy} className="button primary">Save feedback</button></form></section>
  </>}
