/**
 * Purpose: Presents the admin-only spam assessment, mandatory checks, point
 * ledgers, AI evidence, package details, and approval action.
 */
// FactorTable renders one auditable point ledger and its evidence reasons.
// Detail loads the complete administrator review and controls approval state.
// approve records the administrator's human approval decision.
import {useEffect,useState} from 'react';import {ArrowLeft,CheckCircle2,ShieldAlert} from 'lucide-react';import {Link,useParams} from 'react-router-dom';import {api} from '../api';import {Badge,Score} from '../components';
function FactorTable({title,kind,items,total}){return <div className={`factor-panel ${kind}`}><div className="factor-title"><h2>{title}</h2><strong>{items.reduce((n,x)=>n+x.points,0).toFixed(1)} / {total}</strong></div>{items.map(x=><article key={x.code}><div><b>{x.label}</b><p>{x.reason}</p></div><span>{x.points.toFixed(1)} / {x.max_points}</span></article>)}</div>}
export default function Detail(){const{id}=useParams();const[item,setItem]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState('');useEffect(()=>{api.adminGet(id).then(setItem).catch(e=>setError(e.message))},[id]);async function approve(){setBusy(true);try{setItem(await api.approve(id))}catch(e){setError(e.message)}finally{setBusy(false)}}if(error&&!item)return <p className="error">{error}</p>;if(!item)return <p>Loading…</p>;return <><Link className="back" to="/admin"><ArrowLeft size={17}/>Back to queue</Link><header><div><p className="eyebrow">AUTOMATIC SPAM ASSESSMENT</p><h1>{item.name}</h1><p>{item.service_title} · {item.category}</p></div><div className="actions"><Badge level={item.risk_level}/>{item.status!=='approved'&&<button disabled={busy} className="button primary" onClick={approve}>{busy?'Approving…':'Approve service'}</button>}</div></header>{error&&<p className="error">{error}</p>}<section className="mandatory panel"><div><p className="eyebrow">MANDATORY SCORING SERVICES</p><h2>All automatic checks</h2></div>{item.mandatory_services.map(s=><span key={s.code}><CheckCircle2 size={16}/>{s.name}<b>Required</b></span>)}</section><section className="score-panel panel"><Score label="Trust Score" value={item.trust_score} type="trust"/><Score label="Spam Risk Score" value={item.risk_score} type="risk"/><div className="confidence"><span>{item.combined_assessment.method}</span><strong>{item.confidence}% confidence</strong></div></section><section className="factor-grid"><FactorTable title="Spam Risk Factors" kind="risk" items={item.risk_factors} total={10}/><FactorTable title="Trust Score Factors" kind="trust" items={item.trust_factors} total={10}/></section><section className="detail-grid"><div className="panel profile"><h2>Service and package</h2><dl><dt>Package</dt><dd>{item.package_name}</dd><dt>Price</dt><dd>{item.price_or_range}</dd><dt>Timeline</dt><dd>{item.delivery_timeline}</dd><dt>Inclusions</dt><dd>{item.package_details}</dd><dt>Offer</dt><dd>{item.special_offer||'None'}</dd><dt>Description</dt><dd>{item.description}</dd><dt>Website</dt><dd>{item.website||'Not supplied'}</dd></dl></div><div className="panel ai-card"><p className="eyebrow">LOCAL AI SPAM REVIEW</p><h2>{item.ai_assessment.model}</h2>{item.ai_assessment.status==='complete'?<><p><b>Spam probability: {item.ai_assessment.spam_probability}%</b></p><h3>Spam indicators</h3><ul>{item.ai_assessment.spam_indicators.map(x=><li key={x}>{x}</li>)}</ul><h3>Trust indicators</h3><ul>{item.ai_assessment.trust_indicators.map(x=><li key={x}>{x}</li>)}</ul><p>{item.ai_assessment.summary}</p></>:<p><ShieldAlert size={16}/> {item.ai_assessment.spam_indicators[0]}</p>}</div></section></>}
