/**
 * Purpose: Collects required vendor address and service details, validates
 * optional identity/media inputs, and starts private automatic assessment.
 */
import {useState} from 'react';
import {Link} from 'react-router-dom';
import {CheckCircle2,Send} from 'lucide-react';
import {api} from '../api';
import {Field} from '../components';

const initial={name:'',phone:'',website:'',address_line1:'',address_line2:'',city:'',state:'',country:'India',pincode:'',aadhaar_number:'',gst_number:'',portfolio_link:'',service_title:'',description:'',category:'Venues',social_links:'',business_registration:'',package_name:'',package_details:'',price_or_range:'',special_offer:''};
const imageTypes=['image/jpeg','image/png','image/webp'],fileTypes=['application/pdf','application/msword','application/vnd.openxmlformats-officedocument.wordprocessingml.document'];

// Validates every optional social link only when the vendor supplies one.
function invalidSocialLinks(value){return value.split('\n').map(x=>x.trim()).filter(Boolean).some(value=>{try{return !['http:','https:'].includes(new URL(value).protocol)}catch{return true}})}
// Validates image count, media types, and configured browser-side size limits.
function validateUploads(images,file){if(images.length>5)return 'Upload a maximum of five service images.';if(images.some(x=>!imageTypes.includes(x.type)||x.size>5*1024*1024))return 'Images must be JPEG, PNG, or WebP and no larger than 5 MB each.';if(file&&(!fileTypes.includes(file.type)||file.size>10*1024*1024))return 'The supporting file must be PDF, DOC, or DOCX and no larger than 10 MB.';return ''}

// Collects vendor data without displaying private assessment results.
export default function VendorForm(){
  const[form,setForm]=useState(initial),[images,setImages]=useState([]),[attachment,setAttachment]=useState(null),[result,setResult]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[attempted,setAttempted]=useState(false),[socialInvalid,setSocialInvalid]=useState(false),[uploadInvalid,setUploadInvalid]=useState(false);
  // Keeps controlled text state synchronized and normalizes GST to uppercase.
  const change=e=>{const value=e.target.name==='gst_number'?e.target.value.toUpperCase():e.target.value;setForm({...form,[e.target.name]:value});if(e.target.name==='social_links')setSocialInvalid(false)};
  // Validates inputs, uploads optional media, and creates the assessed submission.
  async function submit(e){e.preventDefault();setAttempted(true);setError('');if(!e.currentTarget.checkValidity()){setError('Please correct the highlighted required fields or invalid formats.');e.currentTarget.querySelector(':invalid')?.focus();return}if(invalidSocialLinks(form.social_links)){setSocialInvalid(true);setError('Each social link must be a complete http:// or https:// URL.');return}const uploadError=validateUploads(images,attachment);if(uploadError){setUploadInvalid(true);setError(uploadError);return}setBusy(true);try{const uploads=(images.length||attachment)?await api.vendorUpload(images,attachment):{images:[],file:null};setResult(await api.vendorCreate({...form,website:form.website||null,portfolio_link:form.portfolio_link||null,package_name:form.package_name||null,package_details:form.package_details||null,price_or_range:form.price_or_range||null,aadhaar_number:form.aadhaar_number||null,gst_number:form.gst_number||null,social_links:form.social_links.split('\n').map(x=>x.trim()).filter(Boolean),business_registration:form.business_registration||null,special_offer:form.special_offer||null,...uploads}))}catch(e){setError(e.message)}finally{setBusy(false)}}
  if(result)return <div className="result-card"><CheckCircle2 size={40}/><h1>Submitted for review</h1><p>Your service and optional media were submitted. Internal scores remain visible only to administrators.</p><Link className="button primary" to="/vendor">View my submissions</Link></div>;
  return <><header><div><p className="eyebrow">VENDOR PORTAL</p><h1>Register your service</h1><p>Fields marked <b className="required-star">*</b> are required. Screening runs privately in the background.</p></div></header><form noValidate className={`panel form ${attempted?'validated':''}`} onSubmit={submit}>
    <div className="form-section"><h2>Business and service</h2><div className="grid">
      <Field required label="Business name"><input required minLength="2" name="name" value={form.name} onChange={change}/></Field><Field required label="Category"><select required name="category" value={form.category} onChange={change}><option>Venues</option><option>Catering</option><option>Photography & Videography</option><option>Decor & Florist</option><option>Wedding Planning</option><option>DJ & Entertainment</option><option>Makeup & Bridal</option><option>Invitations & Stationery</option><option>Other</option></select></Field>
      <Field required label="Phone"><input required pattern="[0-9+()\-\s]{7,40}" title="Use 7–40 digits and common phone symbols" name="phone" value={form.phone} onChange={change}/></Field><Field label="Website (optional)"><input type="url" placeholder="https://example.com" name="website" value={form.website} onChange={change}/></Field>
      <Field label="Portfolio link (optional)"><input type="url" name="portfolio_link" value={form.portfolio_link} onChange={change} placeholder="https://instagram.com/yourwork"/></Field><Field required label="Service title"><input required minLength="3" name="service_title" value={form.service_title} onChange={change}/></Field>
      <Field required label="Detailed service description" className="wide"><textarea required minLength="10" rows="6" name="description" value={form.description} onChange={change} placeholder="Explain process, deliverables, intended customer, and limitations."/></Field>
    </div></div>
    <div className="form-section address-section"><h2>Registered address <span>Required</span></h2><div className="grid">
      <Field required label="Address line 1" className="wide"><input required minLength="3" name="address_line1" value={form.address_line1} onChange={change}/></Field><Field required label="Address line 2" className="wide"><input required minLength="2" name="address_line2" value={form.address_line2} onChange={change}/></Field>
      <Field required label="City"><input required minLength="2" name="city" value={form.city} onChange={change}/></Field><Field required label="State"><input required minLength="2" name="state" value={form.state} onChange={change}/></Field><Field required label="Country"><input required minLength="2" name="country" value={form.country} onChange={change}/></Field><Field required label="Pincode"><input required pattern="[A-Za-z0-9][A-Za-z0-9 \-]{2,11}" name="pincode" value={form.pincode} onChange={change}/></Field>
    </div></div>
    <div className="form-section package-section"><h2>Package / offer details <span>Optional</span></h2><p className="section-help">Add these only if you already offer fixed packages. Customers can still discover and book your service without them.</p><div className="grid"><Field label="Package name (optional)"><input minLength="2" name="package_name" value={form.package_name} onChange={change}/></Field><Field label="Price or price range (optional)"><input name="price_or_range" value={form.price_or_range} onChange={change}/></Field><Field label="Special offer (optional)"><input name="special_offer" value={form.special_offer} onChange={change}/></Field><Field label="Package inclusions and exclusions (optional)" className="wide"><textarea minLength="10" rows="5" name="package_details" value={form.package_details} onChange={change}/></Field></div></div>
    <div className="form-section"><h2>Optional verification</h2><div className="grid"><Field label="Aadhaar number (optional)"><input inputMode="numeric" pattern="[0-9]{12}" title="Enter exactly 12 digits" name="aadhaar_number" value={form.aadhaar_number} onChange={change}/></Field><Field label="GST number (optional)"><input pattern="[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z][1-9A-Z]Z[0-9A-Z]" title="Enter a valid 15-character GSTIN" maxLength="15" name="gst_number" value={form.gst_number} onChange={change}/></Field><Field label="Social URLs (optional, one per line)" className={socialInvalid?'invalid-field':''}><textarea name="social_links" value={form.social_links} onChange={change}/></Field><Field label="Business registration (optional)"><input name="business_registration" value={form.business_registration} onChange={change}/></Field></div></div>
    <div className="form-section"><h2>Service media <span>Optional</span></h2><div className="grid"><Field label="Service photos (up to 5)" className={uploadInvalid?'invalid-field':''}><input type="file" multiple accept="image/jpeg,image/png,image/webp" onChange={e=>{setImages([...e.target.files]);setUploadInvalid(false)}}/><small>JPEG, PNG, or WebP; maximum 5 MB each.</small></Field><Field label="Supporting file"><input type="file" accept=".pdf,.doc,.docx" onChange={e=>{setAttachment(e.target.files[0]||null);setUploadInvalid(false)}}/><small>PDF, DOC, or DOCX; maximum 10 MB.</small></Field></div></div>
    {error&&<p className="error">{error}</p>}<div className="form-actions"><p>Automatic spam screening occurs privately after submission.</p><button disabled={busy} className="button primary"><Send size={18}/>{busy?'Uploading & screening…':'Submit service'}</button></div>
  </form></>;
}
